### ISSUE TITLE
Can't build on OSX

### ISSUE THREAD

**Issue by vicwomg** [mfvargo/rtjam#18]
Running 11.2.1 big sur

First of all the clone command in the readme ( `git clone --recurse-submodules git@github.com:mfvargo/rtjam.git` ) didn't seem to work. Permissions error connecting to the host. 

```
Cloning into 'rtjam'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I used this instead:
`git clone --recurse-submodules https://github.com/mfvargo/rtjam.git`

But I get an error when running make. Attached.
[rtjam_error.txt](https://github.com/mfvargo/rtjam/files/6016866/rtjam_error.txt)

**Comment by mfvargo** [comment]
Good catch on the git clone.  I forget that I have the ssh keys with github so the git@github.com works.

I can reproduce the compile error in broadcast.cpp on my mac as well.  Not sure why the C++ compiler on the mac does not like that where gcc on linux and raspberry pi os is fine with that.  I'll need to dig into that.

**Comment by mfvargo** [comment]
New direction will no longer support osx for the client.
